Committing workflows

diff --git a/.github/workflows/databases_mysql_create_README_md.yml b/.github/workflows/databases_mysql_create_README_md.yml
--- a/.github/workflows/databases_mysql_create_README_md.yml
+++ b/.github/workflows/databases_mysql_create_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 11 * * 4'
   workflow_dispatch: 
 
 name: 'databases/mysql/create/README.md'
@@ -15,18 +17,17 @@ jobs:
           
           if [[ -z $RESOURCE_GROUP ]]; then
           export RESOURCE_GROUP=java-on-azure-$RANDOM
-          export REGION=westus2
+          export REGION=southcentralus
           fi
           
           az group create --name $RESOURCE_GROUP --location $REGION
-          export MYSQL_NAME=mysql-$RANDOM
-          export MYSQL_USERNAME=mysql
-          export MYSQL_PASSWORD=p#ssw0rd-$RANDOM
+          
           if [[ -z $MYSQL_NAME ]]; then
           export MYSQL_NAME=mysql-$RANDOM
           export MYSQL_USERNAME=mysql
           export MYSQL_PASSWORD=p#ssw0rd-$RANDOM
           fi
+          
           az mysql server create \
           --admin-user $MYSQL_USERNAME \
           --admin-password $MYSQL_PASSWORD \
@@ -35,4 +36,9 @@ jobs:
           --sku B_Gen5_1 \
           --ssl-enforcement Disabled
           
+          export RESULT=$(az mysql server show --name $MYSQL_NAME --resource-group $RESOURCE_GROUP --output tsv --query userVisibleState)
           az group delete --name $RESOURCE_GROUP --yes || true
+          if [[ "$RESULT" != Ready ]]; then
+          echo "Provisioning MySQL " $MYSQL_NAME " failed"
+          exit 1
+          fi
