Committing workflows

diff --git a/.github/workflows/databases_postgresql_get-country_README_md.yml b/.github/workflows/databases_postgresql_get-country_README_md.yml
--- a/.github/workflows/databases_postgresql_get-country_README_md.yml
+++ b/.github/workflows/databases_postgresql_get-country_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 14 * * 2'
   workflow_dispatch: 
 
 name: 'databases/postgresql/get-country/README.md'
@@ -65,4 +67,10 @@ jobs:
           cd ../../..
           
           
+          cd databases/mysql/get-country
+          export RESULT=$(java -jar target/get-country.jar jdbc:postgresql://$POSTGRESQL_DNS_NAME:5432/demo?ssl=true\&sslmode=require $POSTGRESQL_CLIENT_USERNAME $POSTGRESQL_PASSWORD USA)
+          cd ../../..
           az group delete --name $RESOURCE_GROUP --yes || true
+          if [[ "$RESULT" != *"United States"* ]]; then
+          echo "Unable to get the correct country information"
+          exit 1
