Committing workflows

diff --git a/.github/workflows/databases_mysql_get-country_README_md.yml b/.github/workflows/databases_mysql_get-country_README_md.yml
--- a/.github/workflows/databases_mysql_get-country_README_md.yml
+++ b/.github/workflows/databases_mysql_get-country_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 13 * * 5'
   workflow_dispatch: 
 
 name: 'databases/mysql/get-country/README.md'
@@ -61,4 +63,9 @@ jobs:
           cd ../../..
           
           
+          export RESULT=$(java -jar target/get-country.jar jdbc:mysql://$MYSQL_DNS_NAME:3306/demo?useSSL=true\&requireSSL=true $MYSQL_CLIENT_USERNAME $MYSQL_PASSWORD USA)
           az group delete --name $RESOURCE_GROUP --yes || true
+          if [[ "$RESULT" != "*United States*" ]]; then
+          echo "Unable to get the correct country information"
+          exit 1
+          fi
