Committing workflows

diff --git a/.github/workflows/eventhubs_receive-event_README_md.yml b/.github/workflows/eventhubs_receive-event_README_md.yml
--- a/.github/workflows/eventhubs_receive-event_README_md.yml
+++ b/.github/workflows/eventhubs_receive-event_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 7 * * 3'
   workflow_dispatch: 
 
 name: 'eventhubs/receive-event/README.md'
@@ -111,8 +113,16 @@ jobs:
           --query primaryConnectionString \
           --output tsv)
           mvn clean install
-          java -jar targert/send-event.jar
+          
+          export RESULT=$(java -jar target/send-event.jar)
+          
           mvn clean install
-          java -jar targert/receive-event.jar
+          
+          export RESULT=$(java -jar target/receive-event.jar)
+          
           
           az group delete --name $RESOURCE_GROUP --yes || true
+          if [[ "$RESULT" != 'Received: this is an event' ]]; then
+          echo "Error when receiving event to EventHub"
+          exit 1
+          fi
diff --git a/.github/workflows/eventhubs_send-event_README_md.yml b/.github/workflows/eventhubs_send-event_README_md.yml
--- a/.github/workflows/eventhubs_send-event_README_md.yml
+++ b/.github/workflows/eventhubs_send-event_README_md.yml
@@ -1,4 +1,6 @@
 on: 
+  schedule: 
+    - cron: '0 7 * * 4'
   workflow_dispatch: 
 
 name: 'eventhubs/send-event/README.md'
@@ -65,6 +67,12 @@ jobs:
           --query primaryConnectionString \
           --output tsv)
           mvn clean install
-          java -jar targert/send-event.jar
+          
+          export RESULT=$(java -jar target/send-event.jar)
+          
           
           az group delete --name $RESOURCE_GROUP --yes || true
+          if [[ "$RESULT" != 'Event was sent successfully' ]]; then
+          echo "Error when sending event to EventHub"
+          exit 1
+          fi
